// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZp3SfWwjORuMKGmCuypU2z94Wf0401A',
    appId: '1:63227226451:web:456a1df54a9c01985b19a6',
    messagingSenderId: '63227226451',
    projectId: 'zibzo-eeea3',
    authDomain: 'zibzo-eeea3.firebaseapp.com',
    storageBucket: 'zibzo-eeea3.firebasestorage.app',
    measurementId: 'G-W4294JHCK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUpss-rFkzShYSM2BeSEJkgNgOA2zm7Jg',
    appId: '1:63227226451:android:bf3ce60bc4f442b15b19a6',
    messagingSenderId: '63227226451',
    projectId: 'zibzo-eeea3',
    storageBucket: 'zibzo-eeea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFVBodWMO49W2Vtq14ISvndxP_O5c5R0',
    appId: '1:63227226451:ios:1f6a412d9f277f775b19a6',
    messagingSenderId: '63227226451',
    projectId: 'zibzo-eeea3',
    storageBucket: 'zibzo-eeea3.firebasestorage.app',
    iosBundleId: 'com.youshah.zibzoApp',
  );
}
