name: ZibZo APP CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Analyze and Test
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.x"

      - name: Flutter Clean
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build:
    name: Build APK
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GPG (for macOS)
        run: |
          brew install gnupg

      - name: Decrypt Keystore
        env:
          GPG_KEY: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$GPG_KEY" | gpg --batch --passphrase-fd 0 --output android/app/keystore.jks --decrypt android/app/keystore.jks.gpg

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      - name: Get Dependencies
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean

      - name: Build Release APK
        run: flutter build appbundle --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*
