name: ZibZo APP CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - test

jobs:
  test:
    name: Analyze and Test
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          architecture: x64
          cache: true

      # Clean previous builds
      - name: Clean Flutter
        run: flutter clean

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze the code
      - name: Analyze Code
        run: flutter analyze

      # Run tests
      - name: Run Tests
        run: flutter test

  build:
    name: Build APK
    runs-on: macos-latest
    needs: test # Ensures tests are completed first
    if: github.event_name == 'pull_request' # Run only on PR events
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          architecture: x64
          cache: true

      # Build APK
      - name: Build APK
        run: flutter build apk --debug --split-per-abi

      # Display Flutter version
      - name: Flutter Version
        run: flutter --version

      # Upload the built APK (optional)
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
