name: ZibZo APP CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Analyze and Test
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: stable
          architecture: x64
          cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.x"

  build:
    name: Build APK
    runs-on: macos-latest
    needs: test # Ensures that the test job runs before this job
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          cache: true

      # 12
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runner's shell
      - name: Start release build
        run: |
          flutter clean
          flutter pub get
          flutter build appbundle --release --no-tree-shake-icons

      # Upload Build Artifact (Optional)
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
