name: ZibZo APP CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Analyze and Test
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: stable
          architecture: x64
          cache: true

      # Setup Java for Android builds
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"
      # Flutter clean
      - name: Clean Flutter
        run: flutter clean

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze the code
      - name: Analyze Code
        run: flutter analyze

      # Run tests
      - name: Run Tests
        run: flutter test

  build:
    name: Build APK
    runs-on: macos-latest
    needs: test # Ensures that the test job runs before this job
    if: startsWith(github.ref, 'refs/heads/main_') || startsWith(github.ref, 'refs/heads/test_')
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/app/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: "stable"
          cache: true

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Flutter clean
      - name: Flutter Clean
        run: flutter clean

      # Start release build
      - name: Start release build
        run: flutter build apk --release --split-per-abi

      # Upload Build Artifact (Optional)
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
