name: ZibZo CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  flutter:
    name: Zibzo
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter Analyzer
      - name: Analyze Code
        run: flutter analyze

      # Run Flutter Tests
      - name: Run Tests
        run: flutter test

      # Build APK (or iOS app)
      - name: Build APK
        run: flutter build apk --debug --split-per-abi

      # Display Flutter Version
      - name: Flutter Version
        run: flutter --version

      # Upload Build Artifact (Optional)
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
